# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_trunc_ndist
#'
#' Truncated normal distribution (mean 1, respective upper and lower limits of
#' 0 and 2).
#'
#' @param len Number of elements to be simulated
#' @param sd Standard deviation
#'
#' @return A vector of truncated normally distributed values
#'
rcpp_trunc_ndist <- function(len, sd) {
    .Call('tnorm_rcpp_trunc_ndist', PACKAGE = 'tnorm', len, sd)
}

